# Generated by Django 4.1.7 on 2023-03-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('current_token', models.IntegerField(default=0)),
                ('next_token', models.IntegerField(default=1)),
            ],
        ),
    ]
