# Generated by Django 4.1.7 on 2023-03-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cafe_id_customuser_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='current_token',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='next_token',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
