# Generated by Django 4.1.7 on 2023-03-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cafe_logos/'),
        ),
    ]
