# Generated by Django 4.1.7 on 2023-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_address_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='logo',
        ),
        migrations.AddField(
            model_name='cafe',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cafe_logos/'),
        ),
    ]
