# Generated by Django 4.1.7 on 2023-04-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='song_link',
            new_name='playlist_name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_name',
        ),
    ]
