# Generated by Django 4.1.7 on 2023-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='song_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
