# Generated by Django 4.1.7 on 2023-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_queue_song_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='token_no',
            field=models.IntegerField(null=True),
        ),
    ]
