# Generated by Django 4.1.7 on 2023-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_queue_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
    ]
