# Generated by Django 4.1.7 on 2023-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_song_is_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
    ]
