# Generated by Django 4.1.7 on 2023-04-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_queue_is_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_played',
        ),
    ]
