# Generated by Django 4.1.7 on 2023-04-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_song_is_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='song_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
