# Generated by Django 4.1.7 on 2023-05-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_queue_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='bl',
        ),
        migrations.RemoveField(
            model_name='address',
            name='br',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tl',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tr',
        ),
        migrations.AddField(
            model_name='address',
            name='BottomRight_coord_lat',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='BottomRight_coord_long',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='bottomLeft_coord_lat',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='bottomLeft_coord_long',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='topLeft_coord_lat',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='topLeft_coord_long',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='topRight_coord_lat',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='topRight_coord_long',
            field=models.FloatField(default=0.0, max_length=25),
        ),
    ]
