# Generated by Django 4.1.7 on 2023-05-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_mobileappusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
